<a href="https://colab.research.google.com/github/estergracia/estergracia/blob/Crawling-dataset/Crawl_Data_Twitter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#@title Twitter Auth Token

twitter_auth_token = 'a6fac683f5f8b4a42619f716cfe1b96c2fef5f69' # change this auth token

In [ ]:
#@title Twitter Auth Token

twitter_auth_token = '0d0a4b03066c6d3ad2c6c5092e183d96288bc0c9' # change this auth token

In [ ]:
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 https://deb.nodesource.com/node_20.x nodistro InRelease
Ign:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy Release
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:12 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.18).
gnupg is already the newest version (2.2.27-3ubuntu2.1).
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
gpg: cannot open '/dev/tty': No such device or address
curl: (23) Failed writing body
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy Release
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (20.17.0-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 54 not upgraded.
v20.17.0

In [ ]:
# Crawl Data

filename = 'garudaindonesia.csv'
search_keyword = 'pesawat garuda since:2020-01-01 until:2020-03-01'
limit = 450

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1)
Filling in keywords: pesawat garuda since:2020-01-01 until:2020-03-01

 (2) (3)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 18


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 33

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 42


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 53


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 69

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 86

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 100

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 116

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 132


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 144

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 153


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 169


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 179


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 187


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 196

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 206

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 221

--Taking a break, waiting for 10 seconds...


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 229


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 235


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 244


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 254


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 264


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 273


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 287

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 300

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 315

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 324

--Taking a break, waiting for 10 seconds...


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 335


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 344


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 352


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 364


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 376


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 389


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 393


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 404


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 414

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 428

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 439


Your tweets saved to: /content/tweets-data/garudaindonesia.csv
Total tweets saved: 452
Got 452 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1233717808980062209,Sat Feb 29 11:37:01 +0000 2020,0,[Berita Malaysia App] Liputan6: KTT ASEAN di A...,1233717808980062209,NaN,NaN,in,"DKI Jakarta, Indonesia",0,0,0,https://x.com/IsmailMunthe8/status/12337178089...,1209314507224276992,IsmailMunthe8
1,1233712555153088512,Sat Feb 29 11:16:09 +0000 2020,0,Lebih Efisien Sewa Pesawat Garuda Lawatan Pres...,1233712555153088512,https://pbs.twimg.com/media/ER8HB-IXsAEehcJ.jpg,NaN,in,NaN,0,0,0,https://x.com/matafakta1/status/12337125551530...,1215448767857483776,matafakta1
2,1233662028021039109,Sat Feb 29 10:51:56 +0000 2020,0,@alvinlie21 @msaid_didu Keren Om Alvin utk pos...,1233706463400316928,NaN,alvinlie21,in,NaN,0,1,0,https://x.com/CintaNK14326926/status/123370646...,1091597648518238208,CintaNK14326926
3,1233700827950239744,Sat Feb 29 10:29:33 +0000 2020,1,KTT ASEAN di AS Ditunda Begini Nasib Pesawat G...,1233700827950239744,NaN,NaN,in,Indonesia,0,0,0,https://x.com/merdekadotcom/status/12337008279...,456426648,merdekadotcom
4,1233700337787097089,Sat Feb 29 10:27:36 +0000 2020,0,#tiketmurahmeriah #tiketpromo #garuda tiket pe...,1233700337787097089,NaN,NaN,in,"Bali, Indonesia",0,0,0,https://x.com/TiketPesawatPro/status/123370033...,3242736720,TiketPesawatPro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,1224311987720470530,Mon Feb 03 12:41:39 +0000 2020,0,#iata #aviation #travel #flight #jeddah #ibada...,1224311987720470530,NaN,NaN,qme,NaN,0,0,0,https://x.com/RamaYenti/status/122431198772047...,1170920982,RamaYenti
448,1223560519547637760,Mon Feb 03 07:49:22 +0000 2020,0,@ontasirkus Klo liat daftar pesawat2 charteran...,1224238432597098496,NaN,onsir_,in,"Jakarta Capital Region, Indone",0,0,0,https://x.com/Amelia_D/status/1224238432597098496,60557720,Amelia_D
449,1224230765082202112,Mon Feb 03 07:18:54 +0000 2020,0,Tak Ada Pesawat Garuda Terbang ke dan dari Chi...,1224230765082202112,NaN,NaN,in,NaN,0,0,0,https://x.com/topinfo_id/status/12242307650822...,1215289012551741443,topinfo_id
450,1224216027409502208,Mon Feb 03 06:20:20 +0000 2020,0,Garuda Buka Usaha Perawatan Pesawat di Austral...,1224216027409502208,NaN,NaN,in,"Denpasar, Bali",0,0,0,https://x.com/nusabalicom/status/1224216027409...,2655442453,nusabalicom
451,1224199469249351680,Mon Feb 03 05:14:32 +0000 2020,0,Tak Ada Pesawat Garuda Terbang ke dan dari Chi...,1224199469249351680,https://pbs.twimg.com/media/EP067gAUwAAR9Sc.jpg,NaN,in,"Jambi, Indonesia",0,0,0,https://x.com/AviaWisata/status/12241994692493...,1049198270,AviaWisata

In [ ]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 452.

In [ ]:
# Crawl Data

filename = 'garudaindonesia2.csv'
search_keyword = 'pesawat garuda since:2020-03-02 until:2020-05-01'
limit = 450

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: pesawat garuda since:2020-03-02 until:2020-05-01

 (3) (4)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 15


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 33

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 47


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 57


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 71

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 82


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 93


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 105

--Taking a break, waiting for 10 seconds...


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 120

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 139

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 149


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 161


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 170


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 181

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 195

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 209

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 224

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 234


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 249


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 262


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 273


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 289

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 300


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 310

--Taking a break, waiting for 10 seconds...


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 320


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 332

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 340

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 351


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 356

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 370

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 377


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 390

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 397


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 406


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 413

--Taking a break, waiting for 10 seconds...


Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 426

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 435

-- Scrolling... (1) (2) (3)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 449

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/garudaindonesia2.csv
Total tweets saved: 458
Got 458 tweets, done scrolling...
⠙

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1255632464229228544,Wed Apr 29 22:58:02 +0000 2020,0,#pariwisatamedan #pariwisatasumaterautara #par...,1255632464229228544,NaN,NaN,in,"Bali, Indonesia",0,0,0,https://x.com/TiketPesawatPro/status/125563246...,3242736720,TiketPesawatPro
1,1255610331373551617,Wed Apr 29 21:30:05 +0000 2020,2,Pesawat Garuda kembali ke Jakarta juga mengang...,1255610331373551617,NaN,NaN,in,NaN,0,0,0,https://x.com/IDNTimes/status/1255610331373551617,388190238,IDNTimes
2,1255513418238492680,Wed Apr 29 15:04:59 +0000 2020,0,Bila Dulu Tidak ada Korupsi atau Markup Pasti ...,1255513418238492680,NaN,NaN,in,Indonesia,0,0,0,https://x.com/jondivar/status/1255513418238492680,131720346,jondivar
3,1255505277354467328,Wed Apr 29 14:32:38 +0000 2020,0,Angkasa Pura II: Ada 13 penumpang pesawat garu...,1255505277354467328,NaN,NaN,in,Aceh,0,0,0,https://x.com/aceh_antaranews/status/125550527...,3799304234,aceh_antaranews
4,1255497765456576520,Wed Apr 29 14:02:47 +0000 2020,0,Terpapar corona Garuda (GIAA) nego biaya sewa ...,1255497765456576520,NaN,NaN,in,NaN,0,0,0,https://x.com/mag_berita/status/12554977654565...,1197765630964846592,mag_berita
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,1240300953972035584,Wed Mar 18 15:36:05 +0000 2020,8,Direktur Utama Garuda Indonesia Irfan Setiaput...,1240300953972035584,NaN,NaN,in,Jakarta,1,0,0,https://x.com/kompascom/status/124030095397203...,23343960,kompascom
454,1240292569277280259,Wed Mar 18 15:02:46 +0000 2020,0,Pesawat Garuda Indonesia A380 Jumbo B... https...,1240292569277280259,NaN,NaN,in,NaN,0,0,0,https://x.com/ciustoys/status/1240292569277280259,3444516746,ciustoys
455,1240243020089503744,Wed Mar 18 11:45:53 +0000 2020,0,mau keluar kota dengan fasilitas yg nyaman dan...,1240243020089503744,https://pbs.twimg.com/ext_tw_video_thumb/12402...,NaN,in,NaN,0,0,0,https://x.com/baruga_travel/status/12402430200...,1220678457073364993,baruga_travel
456,1240207864221724672,Wed Mar 18 09:26:11 +0000 2020,0,Ijin diajukan sejak 10 maret. Jika nanti diacc...,1240207864221724672,NaN,NaN,in,"Surakarta, Jawa Tengah",0,0,0,https://x.com/triunt/status/1240207864221724672,51996865,triunt
457,1240192943459168256,Wed Mar 18 09:11:16 +0000 2020,2,@FerdinandHaean2 Tanya Jokowi lah knp plantat ...,1240204110902620160,NaN,FerdinandHaean2,in,dimana aja bebas sultan mah,0,0,0,https://x.com/DunguToing/status/12402041109026...,1210797425708781574,DunguToing

In [ ]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 458.

In [ ]:
import pandas as pd

# Membaca file CSV pertama
file1 = pd.read_csv('tweets-data/garudaindonesia.csv')

# Membaca file CSV kedua
file2 = pd.read_csv('tweets-data/garudaindonesia2.csv')

# Menggabungkan kedua DataFrame
combined = pd.concat([file1, file2], ignore_index=True)

# Menyimpan hasil gabungan ke file baru
combined.to_csv('tweets-data/garudaindonesiajan20-mei20.csv', index=False)

In [ ]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"tweets-data/garudaindonesiajan20-mei20.csv"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1233717808980062209,Sat Feb 29 11:37:01 +0000 2020,0,[Berita Malaysia App] Liputan6: KTT ASEAN di A...,1233717808980062209,NaN,NaN,in,"DKI Jakarta, Indonesia",0,0,0,https://x.com/IsmailMunthe8/status/12337178089...,1209314507224276992,IsmailMunthe8
1,1233712555153088512,Sat Feb 29 11:16:09 +0000 2020,0,Lebih Efisien Sewa Pesawat Garuda Lawatan Pres...,1233712555153088512,https://pbs.twimg.com/media/ER8HB-IXsAEehcJ.jpg,NaN,in,NaN,0,0,0,https://x.com/matafakta1/status/12337125551530...,1215448767857483776,matafakta1
2,1233662028021039109,Sat Feb 29 10:51:56 +0000 2020,0,@alvinlie21 @msaid_didu Keren Om Alvin utk pos...,1233706463400316928,NaN,alvinlie21,in,NaN,0,1,0,https://x.com/CintaNK14326926/status/123370646...,1091597648518238208,CintaNK14326926
3,1233700827950239744,Sat Feb 29 10:29:33 +0000 2020,1,KTT ASEAN di AS Ditunda Begini Nasib Pesawat G...,1233700827950239744,NaN,NaN,in,Indonesia,0,0,0,https://x.com/merdekadotcom/status/12337008279...,456426648,merdekadotcom
4,1233700337787097089,Sat Feb 29 10:27:36 +0000 2020,0,#tiketmurahmeriah #tiketpromo #garuda tiket pe...,1233700337787097089,NaN,NaN,in,"Bali, Indonesia",0,0,0,https://x.com/TiketPesawatPro/status/123370033...,3242736720,TiketPesawatPro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905,1240300953972035584,Wed Mar 18 15:36:05 +0000 2020,8,Direktur Utama Garuda Indonesia Irfan Setiaput...,1240300953972035584,NaN,NaN,in,Jakarta,1,0,0,https://x.com/kompascom/status/124030095397203...,23343960,kompascom
906,1240292569277280259,Wed Mar 18 15:02:46 +0000 2020,0,Pesawat Garuda Indonesia A380 Jumbo B... https...,1240292569277280259,NaN,NaN,in,NaN,0,0,0,https://x.com/ciustoys/status/1240292569277280259,3444516746,ciustoys
907,1240243020089503744,Wed Mar 18 11:45:53 +0000 2020,0,mau keluar kota dengan fasilitas yg nyaman dan...,1240243020089503744,https://pbs.twimg.com/ext_tw_video_thumb/12402...,NaN,in,NaN,0,0,0,https://x.com/baruga_travel/status/12402430200...,1220678457073364993,baruga_travel
908,1240207864221724672,Wed Mar 18 09:26:11 +0000 2020,0,Ijin diajukan sejak 10 maret. Jika nanti diacc...,1240207864221724672,NaN,NaN,in,"Surakarta, Jawa Tengah",0,0,0,https://x.com/triunt/status/1240207864221724672,51996865,triunt
909,1240192943459168256,Wed Mar 18 09:11:16 +0000 2020,2,@FerdinandHaean2 Tanya Jokowi lah knp plantat ...,1240204110902620160,NaN,FerdinandHaean2,in,dimana aja bebas sultan mah,0,0,0,https://x.com/DunguToing/status/12402041109026...,1210797425708781574,DunguToing

In [ ]:
import pandas as pd

# Membaca file CSV
data = pd.read_csv('tweets-data/garudaindonesiajan20-mei20.csv')

# Menampilkan data dalam format tabel
print(data)

# Jika ingin menyimpan dalam format tabel, bisa menggunakan
data.to_excel('tweets-data/garudaindonesiajan20-mei20.xlsx', index=False)  # Menyimpan sebagai file Excel

     conversation_id_str                      created_at  favorite_count  \
0    1233717808980062209  Sat Feb 29 11:37:01 +0000 2020               0
1    1233712555153088512  Sat Feb 29 11:16:09 +0000 2020               0
2    1233662028021039109  Sat Feb 29 10:51:56 +0000 2020               0
3    1233700827950239744  Sat Feb 29 10:29:33 +0000 2020               1
4    1233700337787097089  Sat Feb 29 10:27:36 +0000 2020               0
..                   ...                             ...             ...
905  1240300953972035584  Wed Mar 18 15:36:05 +0000 2020               8
906  1240292569277280259  Wed Mar 18 15:02:46 +0000 2020               0
907  1240243020089503744  Wed Mar 18 11:45:53 +0000 2020               0
908  1240207864221724672  Wed Mar 18 09:26:11 +0000 2020               0
909  1240192943459168256  Wed Mar 18 09:11:16 +0000 2020               2

                                             full_text               id_str  \
0    [Berita Malaysia App] Liputan6: KTT ASEAN di A...  1233717808980062209
1    Lebih Efisien Sewa Pesawat Garuda Lawatan Pres...  1233712555153088512
2    @alvinlie21 @msaid_didu Keren Om Alvin utk pos...  1233706463400316928
3    KTT ASEAN di AS Ditunda Begini Nasib Pesawat G...  1233700827950239744
4    #tiketmurahmeriah #tiketpromo #garuda tiket pe...  1233700337787097089
..                                                 ...                  ...
905  Direktur Utama Garuda Indonesia Irfan Setiaput...  1240300953972035584
906  Pesawat Garuda Indonesia A380 Jumbo B... https...  1240292569277280259
907  mau keluar kota dengan fasilitas yg nyaman dan...  1240243020089503744
908  Ijin diajukan sejak 10 maret. Jika nanti diacc...  1240207864221724672
909  @FerdinandHaean2 Tanya Jokowi lah knp plantat ...  1240204110902620160

                                             image_url  \
0                                                  NaN
1      https://pbs.twimg.com/media/ER8HB-IXsAEehcJ.jpg
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
905                                                NaN
906                                                NaN
907  https://pbs.twimg.com/ext_tw_video_thumb/12402...
908                                                NaN
909                                                NaN

    in_reply_to_screen_name lang                     location  quote_count  \
0                       NaN   in       DKI Jakarta, Indonesia            0
1                       NaN   in                          NaN            0
2                alvinlie21   in                          NaN            0
3                       NaN   in                    Indonesia            0
4                       NaN   in              Bali, Indonesia            0
..                      ...  ...                          ...          ...
905                     NaN   in                      Jakarta            1
906                     NaN   in                          NaN            0
907                     NaN   in                          NaN            0
908                     NaN   in       Surakarta, Jawa Tengah            0
909         FerdinandHaean2   in  dimana aja bebas sultan mah            0

     reply_count  retweet_count  \
0              0              0
1              0              0
2              1              0
3              0              0
4              0              0
..           ...            ...
905            0              0
906            0              0
907            0              0
908            0              0
909            0              0

                                             tweet_url          user_id_str  \
0    https://x.com/IsmailMunthe8/status/12337178089...  1209314507224276992
1    https://x.com/matafakta1/status/12337125551530...  1215448767857483776
2    https://x.com/CintaNK14326926/status/123370646...  1091597648518238208
3    https://x.com/merdekadotcom/status/12337008279...            456426648
4    https://x.com/TiketPesawatPro/status/123370033...           3242736720
..                                                 ...                  ...
905  https://x.com/kompascom/status/124030095397203...             23343960
906  https://x.com/ciustoys/status/1240292569277280259           3444516746
907  https://x.com/baruga_travel/status/12402430200...  1220678457073364993
908    https://x.com/triunt/status/1240207864221724672             51996865
909  https://x.com/DunguToing/status/12402041109026...  1210797425708781574

            username
0      IsmailMunthe8
1         matafakta1
2    CintaNK14326926
3      merdekadotcom
4    TiketPesawatPro
..               ...
905        kompascom
906         ciustoys
907    baruga_travel
908           triunt
909       DunguToing

[910 rows x 15 columns]