<a href="https://colab.research.google.com/github/estergracia/estergracia/blob/Crawling-dataset/Data_Pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load Dataset (from GDrive)

In [ ]:
import gdown
import pandas as pd

# Link : https://drive.google.com/file/d/1cSGaPGRM5wtEsn1fANYwbzLcJyIDOFsa/view?usp=sharing

# Google Drive file ID (ambil dari URL berbagi Google Drive)
file_id = '1cSGaPGRM5wtEsn1fANYwbzLcJyIDOFsa'
url = f'https://drive.google.com/uc?id={file_id}'

# Unduh file dari Google Drive
output = 'GarudaIndonesia_TweetHarvest.csv'
gdown.download(url, output, quiet=False)

# Load dataset
df = pd.read_csv(output)

# Melihat sekilas data
print(df.head())

Downloading...
From: https://drive.google.com/uc?id=1cSGaPGRM5wtEsn1fANYwbzLcJyIDOFsa
To: /content/GarudaIndonesia_TweetHarvest.csv
100%|██████████| 4.50M/4.50M [00:00<00:00, 15.8MB/s]

   conversation_id_str                      created_at favorite_count  \
0  1641699412044021760  Fri Mar 31 07:10:15 +0000 2023              0
1  1641696834186887171  Fri Mar 31 07:00:01 +0000 2023              6
2  1641694446806003712  Fri Mar 31 06:50:33 +0000 2023              1
3  1641694446806003712  Fri Mar 31 06:50:33 +0000 2023              2
4  1641649472781574144  Fri Mar 31 05:32:22 +0000 2023              0

                                           full_text               id_str  \
0  Garuda Indonesia dan Ditjen Imigrasi Resmikan ...  1641699412044021760
1  Pesan tiket Garuda Indonesia ke Sydney sekaran...  1641696834186887171
2  Info lengkap: https://t.co/A30ACwTR3w #GarudaI...  1641694453315555335
3  Kenyamanan tambahan ini dapat dinikmati seluru...  1641694451335852032
4  @Miduk17 Mau ke Garuda Indonesia Merah masih a...  1641674779584528384

                                         image_url in_reply_to_screen_name  \
0                                              NaN                     NaN
1  https://pbs.twimg.com/media/FsRgoQYaAAEh4ji.jpg                     NaN
2                                              NaN         ditjen_imigrasi
3                                              NaN         ditjen_imigrasi
4  https://pbs.twimg.com/media/FshmguUaIAEVpPX.png          JhonSitorus_18

  lang                    location quote_count reply_count retweet_count  \
0   in                       Ambon           0           0             0
1   in                         NaN           0           1             0
2   in   JL HR Rasuna Said Kav x-6           0           3             1
3   in   JL HR Rasuna Said Kav x-6           0           1             1
4   in  Kota Medan, Sumatera Utara           0           0             0

                                           tweet_url          user_id_str  \
0   https://x.com/DiTimur/status/1641699412044021760            631017621
1  https://x.com/IndonesiaGaruda/status/164169683...            155418706
2  https://x.com/ditjen_imigrasi/status/164169445...            990199543
3  https://x.com/ditjen_imigrasi/status/164169445...            990199543
4  https://x.com/Pangemorputra/status/16416747795...  1633044962496462849

          username
0          DiTimur
1  IndonesiaGaruda
2  ditjen_imigrasi
3  ditjen_imigrasi
4    Pangemorputra

## Understanding Data

In [ ]:
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1641699412044021760,Fri Mar 31 07:10:15 +0000 2023,0,Garuda Indonesia dan Ditjen Imigrasi Resmikan ...,1641699412044021760,NaN,NaN,in,Ambon,0,0,0,https://x.com/DiTimur/status/1641699412044021760,631017621,DiTimur
1,1641696834186887171,Fri Mar 31 07:00:01 +0000 2023,6,Pesan tiket Garuda Indonesia ke Sydney sekaran...,1641696834186887171,https://pbs.twimg.com/media/FsRgoQYaAAEh4ji.jpg,NaN,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/164169683...,155418706,IndonesiaGaruda
2,1641694446806003712,Fri Mar 31 06:50:33 +0000 2023,1,Info lengkap: https://t.co/A30ACwTR3w #GarudaI...,1641694453315555335,NaN,ditjen_imigrasi,in,JL HR Rasuna Said Kav x-6,0,3,1,https://x.com/ditjen_imigrasi/status/164169445...,990199543,ditjen_imigrasi
3,1641694446806003712,Fri Mar 31 06:50:33 +0000 2023,2,Kenyamanan tambahan ini dapat dinikmati seluru...,1641694451335852032,NaN,ditjen_imigrasi,in,JL HR Rasuna Said Kav x-6,0,1,1,https://x.com/ditjen_imigrasi/status/164169445...,990199543,ditjen_imigrasi
4,1641649472781574144,Fri Mar 31 05:32:22 +0000 2023,0,@Miduk17 Mau ke Garuda Indonesia Merah masih a...,1641674779584528384,https://pbs.twimg.com/media/FshmguUaIAEVpPX.png,JhonSitorus_18,in,"Kota Medan, Sumatera Utara",0,0,0,https://x.com/Pangemorputra/status/16416747795...,1633044962496462849,Pangemorputra

In [ ]:
df.columns

Index(['conversation_id_str', 'created_at', 'favorite_count', 'full_text',
       'id_str', 'image_url', 'in_reply_to_screen_name', 'lang', 'location',
       'quote_count', 'reply_count', 'retweet_count', 'tweet_url',
       'user_id_str', 'username'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12690 entries, 0 to 12689
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      12689 non-null  object
 1   created_at               12689 non-null  object
 2   favorite_count           12689 non-null  object
 3   full_text                12689 non-null  object
 4   id_str                   12689 non-null  object
 5   image_url                2675 non-null   object
 6   in_reply_to_screen_name  4439 non-null   object
 7   lang                     12689 non-null  object
 8   location                 8228 non-null   object
 9   quote_count              12689 non-null  object
 10  reply_count              12689 non-null  object
 11  retweet_count            12689 non-null  object
 12  tweet_url                12689 non-null  object
 13  user_id_str              12689 non-null  object
 14  username                 12689 non-null  object
dtypes: object(15)
memory usage: 1.5+ MB

Kolom favorite_count, quote_count, reply_count, dan retweet_count seharunya berupa int64 atau float64

## Data Pre-processing

### Ubah tipe data

In [ ]:
df['favorite_count'] = pd.to_numeric(df['favorite_count'], errors='coerce')
df['quote_count'] = pd.to_numeric(df['quote_count'], errors='coerce')
df['reply_count'] = pd.to_numeric(df['reply_count'], errors='coerce')
df['retweet_count'] = pd.to_numeric(df['retweet_count'], errors='coerce')

In [ ]:
# Mengisi nilai NaN dengan 0
df['favorite_count'].fillna(0, inplace=True)
df['quote_count'].fillna(0, inplace=True)
df['reply_count'].fillna(0, inplace=True)
df['retweet_count'].fillna(0, inplace=True)

<ipython-input-6-2e9e4a250275>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['favorite_count'].fillna(0, inplace=True)
<ipython-input-6-2e9e4a250275>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['quote_count'].fillna(0, inplace=True)
<ipython-input-6-2e9e4a250275>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['reply_count'].fillna(0, inplace=True)
<ipython-input-6-2e9e4a250275>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['retweet_count'].fillna(0, inplace=True)

In [ ]:
df['favorite_count'] = df['favorite_count'].astype('int64')
df['quote_count'] = df['quote_count'].astype('int64')
df['reply_count'] = df['reply_count'].astype('int64')
df['retweet_count'] = df['retweet_count'].astype('int64')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12690 entries, 0 to 12689
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      12689 non-null  object
 1   created_at               12689 non-null  object
 2   favorite_count           12690 non-null  int64
 3   full_text                12689 non-null  object
 4   id_str                   12689 non-null  object
 5   image_url                2675 non-null   object
 6   in_reply_to_screen_name  4439 non-null   object
 7   lang                     12689 non-null  object
 8   location                 8228 non-null   object
 9   quote_count              12690 non-null  int64
 10  reply_count              12690 non-null  int64
 11  retweet_count            12690 non-null  int64
 12  tweet_url                12689 non-null  object
 13  user_id_str              12689 non-null  object
 14  username                 12689 non-null  object
dtypes: int64(4), object(11)
memory usage: 1.5+ MB

### Bersihkan Data

In [ ]:
duplikat_count = df.duplicated().sum()
print(duplikat_count)

250

In [ ]:
df_cleaned = df.drop_duplicates()

In [ ]:
df_cleaned.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1641699412044021760,Fri Mar 31 07:10:15 +0000 2023,0,Garuda Indonesia dan Ditjen Imigrasi Resmikan ...,1641699412044021760,NaN,NaN,in,Ambon,0,0,0,https://x.com/DiTimur/status/1641699412044021760,631017621,DiTimur
1,1641696834186887171,Fri Mar 31 07:00:01 +0000 2023,6,Pesan tiket Garuda Indonesia ke Sydney sekaran...,1641696834186887171,https://pbs.twimg.com/media/FsRgoQYaAAEh4ji.jpg,NaN,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/164169683...,155418706,IndonesiaGaruda
2,1641694446806003712,Fri Mar 31 06:50:33 +0000 2023,1,Info lengkap: https://t.co/A30ACwTR3w #GarudaI...,1641694453315555335,NaN,ditjen_imigrasi,in,JL HR Rasuna Said Kav x-6,0,3,1,https://x.com/ditjen_imigrasi/status/164169445...,990199543,ditjen_imigrasi
3,1641694446806003712,Fri Mar 31 06:50:33 +0000 2023,2,Kenyamanan tambahan ini dapat dinikmati seluru...,1641694451335852032,NaN,ditjen_imigrasi,in,JL HR Rasuna Said Kav x-6,0,1,1,https://x.com/ditjen_imigrasi/status/164169445...,990199543,ditjen_imigrasi
4,1641649472781574144,Fri Mar 31 05:32:22 +0000 2023,0,@Miduk17 Mau ke Garuda Indonesia Merah masih a...,1641674779584528384,https://pbs.twimg.com/media/FshmguUaIAEVpPX.png,JhonSitorus_18,in,"Kota Medan, Sumatera Utara",0,0,0,https://x.com/Pangemorputra/status/16416747795...,1633044962496462849,Pangemorputra

#### Missing Values

In [ ]:
missing_values = df_cleaned[df_cleaned.isnull().any(axis=1)]
missing_values

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1641699412044021760,Fri Mar 31 07:10:15 +0000 2023,0,Garuda Indonesia dan Ditjen Imigrasi Resmikan ...,1641699412044021760,NaN,NaN,in,Ambon,0,0,0,https://x.com/DiTimur/status/1641699412044021760,631017621,DiTimur
1,1641696834186887171,Fri Mar 31 07:00:01 +0000 2023,6,Pesan tiket Garuda Indonesia ke Sydney sekaran...,1641696834186887171,https://pbs.twimg.com/media/FsRgoQYaAAEh4ji.jpg,NaN,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/164169683...,155418706,IndonesiaGaruda
2,1641694446806003712,Fri Mar 31 06:50:33 +0000 2023,1,Info lengkap: https://t.co/A30ACwTR3w #GarudaI...,1641694453315555335,NaN,ditjen_imigrasi,in,JL HR Rasuna Said Kav x-6,0,3,1,https://x.com/ditjen_imigrasi/status/164169445...,990199543,ditjen_imigrasi
3,1641694446806003712,Fri Mar 31 06:50:33 +0000 2023,2,Kenyamanan tambahan ini dapat dinikmati seluru...,1641694451335852032,NaN,ditjen_imigrasi,in,JL HR Rasuna Said Kav x-6,0,1,1,https://x.com/ditjen_imigrasi/status/164169445...,990199543,ditjen_imigrasi
5,1641664752769445888,Fri Mar 31 05:08:51 +0000 2023,0,@rahmadidr Baik terima kasih karena telah bers...,1641668858573647873,NaN,rahmadidr,in,NaN,0,0,0,https://x.com/IndonesiaGaruda/status/164166885...,155418706,IndonesiaGaruda
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12685,1489071146037301257,Fri Feb 04 06:44:33 +0000 2022,0,@GunBerkitjau Program ini berlaku untuk minima...,1489490040501596160,NaN,GunBerkitjau,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/148949004...,155418706,IndonesiaGaruda
12686,1489071146037301257,Fri Feb 04 06:26:26 +0000 2022,0,@GunBerkitjau Selain di Kantor Cabang GA pembe...,1489485482165620736,NaN,GunBerkitjau,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/148948548...,155418706,IndonesiaGaruda
12687,1489071146037301257,Fri Feb 04 06:20:13 +0000 2022,0,@GunBerkitjau Benar Kak. Penawaran spesial ini...,1489483914494152709,NaN,GunBerkitjau,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/148948391...,155418706,IndonesiaGaruda
12688,1489461936173760512,Fri Feb 04 04:57:07 +0000 2022,0,@KireiNaHana74 Silakan mengirimkan email ke ti...,1489463004278439936,NaN,KireiNaHana74,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/148946300...,155418706,IndonesiaGaruda
12689,1489418434534281218,Fri Feb 04 02:00:01 +0000 2022,4,Dapatkan berbagai kemudahan dan harga spesial ...,1489418434534281218,https://pbs.twimg.com/media/FKp3UzjUYAESSwB.jpg,NaN,in,NaN,0,2,0,https://x.com/IndonesiaGaruda/status/148941843...,155418706,IndonesiaGaruda

In [ ]:
missing_count = df_cleaned.isnull().sum()
print(missing_count)

conversation_id_str           1
created_at                    1
favorite_count                0
full_text                     1
id_str                        1
image_url                  9836
in_reply_to_screen_name    8094
lang                          1
location                   4385
quote_count                   0
reply_count                   0
retweet_count                 0
tweet_url                     1
user_id_str                   1
username                      1
dtype: int64

In [ ]:
df_cleaned = df.dropna(subset=['full_text'])

In [ ]:
# import re

# # Fungsi untuk membersihkan teks
# def clean_text(text):
#     text = re.sub(r"http\S+", "", text)  # Hapus URL
#     text = re.sub(r"@\w+", "", text)  # Hapus mention
#     text = re.sub(r"#", "", text)  # Hapus hashtag symbol
#     text = re.sub(r"[^A-Za-z0-9\s]", "", text)  # Hapus karakter spesial
#     return text

# df_cleaned['full_text'] = df_cleaned['full_text'].apply(clean_text)

In [ ]:
df_cleaned

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1641699412044021760,Fri Mar 31 07:10:15 +0000 2023,0,Garuda Indonesia dan Ditjen Imigrasi Resmikan ...,1641699412044021760,NaN,NaN,in,Ambon,0,0,0,https://x.com/DiTimur/status/1641699412044021760,631017621,DiTimur
1,1641696834186887171,Fri Mar 31 07:00:01 +0000 2023,6,Pesan tiket Garuda Indonesia ke Sydney sekaran...,1641696834186887171,https://pbs.twimg.com/media/FsRgoQYaAAEh4ji.jpg,NaN,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/164169683...,155418706,IndonesiaGaruda
2,1641694446806003712,Fri Mar 31 06:50:33 +0000 2023,1,Info lengkap: https://t.co/A30ACwTR3w #GarudaI...,1641694453315555335,NaN,ditjen_imigrasi,in,JL HR Rasuna Said Kav x-6,0,3,1,https://x.com/ditjen_imigrasi/status/164169445...,990199543,ditjen_imigrasi
3,1641694446806003712,Fri Mar 31 06:50:33 +0000 2023,2,Kenyamanan tambahan ini dapat dinikmati seluru...,1641694451335852032,NaN,ditjen_imigrasi,in,JL HR Rasuna Said Kav x-6,0,1,1,https://x.com/ditjen_imigrasi/status/164169445...,990199543,ditjen_imigrasi
4,1641649472781574144,Fri Mar 31 05:32:22 +0000 2023,0,@Miduk17 Mau ke Garuda Indonesia Merah masih a...,1641674779584528384,https://pbs.twimg.com/media/FshmguUaIAEVpPX.png,JhonSitorus_18,in,"Kota Medan, Sumatera Utara",0,0,0,https://x.com/Pangemorputra/status/16416747795...,1633044962496462849,Pangemorputra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12685,1489071146037301257,Fri Feb 04 06:44:33 +0000 2022,0,@GunBerkitjau Program ini berlaku untuk minima...,1489490040501596160,NaN,GunBerkitjau,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/148949004...,155418706,IndonesiaGaruda
12686,1489071146037301257,Fri Feb 04 06:26:26 +0000 2022,0,@GunBerkitjau Selain di Kantor Cabang GA pembe...,1489485482165620736,NaN,GunBerkitjau,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/148948548...,155418706,IndonesiaGaruda
12687,1489071146037301257,Fri Feb 04 06:20:13 +0000 2022,0,@GunBerkitjau Benar Kak. Penawaran spesial ini...,1489483914494152709,NaN,GunBerkitjau,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/148948391...,155418706,IndonesiaGaruda
12688,1489461936173760512,Fri Feb 04 04:57:07 +0000 2022,0,@KireiNaHana74 Silakan mengirimkan email ke ti...,1489463004278439936,NaN,KireiNaHana74,in,NaN,0,1,0,https://x.com/IndonesiaGaruda/status/148946300...,155418706,IndonesiaGaruda
12689,1489418434534281218,Fri Feb 04 02:00:01 +0000 2022,4,Dapatkan berbagai kemudahan dan harga spesial ...,1489418434534281218,https://pbs.twimg.com/media/FKp3UzjUYAESSwB.jpg,NaN,in,NaN,0,2,0,https://x.com/IndonesiaGaruda/status/148941843...,155418706,IndonesiaGaruda

## Save File

In [ ]:
df_cleaned.to_csv('/content/GarudaIndonesia_TweetHarvest_Cleaned.csv', index=False)